weights: ./weights/yolov5s.pt
cfg: ./models/yolov5s.yaml
data: ./data/mask_data/data.yaml
hyp: data/hyp.scratch.yaml
epochs: 100
batch_size: 4
img_size:
- 416
- 416
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
log_imgs: 16
log_artifacts: false
workers: 8
project: runs/train
name: mask_yolo5_result
exist_ok: false
quad: false
world_size: 1
global_rank: -1
save_dir: runs\train\mask_yolo5_result2
total_batch_size: 4
